name: CI for Hello World

on: 
  push:
    branches:
      - yamlTesting
  pull_request_target:
    branches:
      - sprint
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
    - name: Checkout Own Repo
      uses: actions/checkout@v3
      with:
        repository: DevOps-Team5-2022/DevOps_Oct2022_Team5_Assignment
        ref: main, yamlTesting
    - name: list our contents
      run: |
        ls
    - name: test with pytest
      run: |
        pytest test.py -v -cov --junitxml=report.xml
