name: CI for Dev
on:
  pull_request:
  
jobs:
  testDevCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11          
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov		  
      - name: Checkout own repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-Team5-2022/DevOps_Oct2022_Team5_Assignment
          fetch-depth: "0"          
      - name: list our contents
        run: |
          ls
      - name: Test Dev's script
        run: |
          pytest Dev_Test.py -v -cov --junitxml=report.xml
      - if: failure()
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          update_existing: true
          search_existing: all
  testQACode:
    needs: testDevCode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11          
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov		  
      - name: Checkout own repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"          
      - name: get QA Pytest
        run: |
          git --version
          git config user.name "Villicus-np"
          git config user.email "kevinkhew01@gmail.com"
          git status
          git checkout remotes/origin/main QA_Test.py

      - name: list our contents
        run: |
          ls
      - name: Test QA's script
        run: |
          pytest QA_Test.py -v -cov --junitxml=report.xml
      - if: failure()
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/missingFeatures.md
          update_existing: true
          search_existing: all
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "report.xml"
          
    - name: Make directory
      run: mkdir -p path/to/artifact

    - name: Move file
      run: mv *.xml path/to/artifact/report.xml

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/
    
    - name: Set environment version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
