name: Test

on:
  push:
    branches:
    - yamlTesting
  pull_request:
    branches:
    - yamlTesting

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: yamlTesting
        
    - name: Use Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        
    - name: Extract test.py from main branch
      run: git checkout main -- path/to/test.py
      
    - name: Run tests
      run: pytest path/to/test.py
