name: CI for Hello World
on:
  push:
    branches:
      - yamlTesting
  pull_request_target:
    branches:
      - yamlTesting
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: Install dependencies
				run: |
					pip install flake8 pytest pytest-cov
		  
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Install Git
        run: sudo apt-get install git    
        
      - name: git
        run: |
          git --version
          git config user.name "Villicus-np"
          git config user.email "kevinkhew01@gmail.com"
          git status
          git tag
          git checkout main -- test.py

      - name: list our contents
        run: |
          ls
