name: CI for Dev
on:
  push:
    branches:
      yamlTesting
  
jobs:
  testDevCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11          
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov		
          
      - name: Install MySQL server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server      
      - name: Start MySQL service
        run: |
          sudo service mysql start
      - name: Stop MySQL service
        run: sudo service mysql stop

      - name: Start MySQL in safe mode
        run: sudo mysqld_safe --skip-grant-tables &

      - name: Connect to MySQL as root
        run: mysql -u root -p"root"

      - name: Change root password to empty
        run: |
          UPDATE mysql.user SET authentication_string='' WHERE User='root';
          FLUSH PRIVILEGES;

      - name: Quit MySQL client
        run: quit

      - name: Stop MySQL service
        run: sudo service mysql stop

      - name: Start MySQL service
        run: sudo service mysql start
      - name: List MySQL users
        run: |
          mysql -u root -e "SELECT User, Host FROM mysql.user;"
