name: CI for Dev
on:
  push:
    branches:
      yamlTesting
  
jobs:
  testDevCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11          
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov		
          
      - name: Install MySQL server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server      
      - name: Start MySQL service
        run: |
          sudo service mysql start
      - name: Create MySQL user
        run: |
          mysql -u root <<EOF
          CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';
          GRANT ALL PRIVILEGES ON *.* TO 'newuser'@'localhost';
          EOF
      - name: List MySQL users
        run: |
          mysql -u root -e "SELECT User, Host FROM mysql.user;"
