name: CI for Hello World

on: 
  push:
    branches:
      - yamlTesting
  pull_request_target:
    branches:
      - sprint
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov

    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git status
        git tag
        git describe
        
    - name: list our contents
      run: |
        ls
    - name: test with pytest
      run: |
        pytest test.py -v -cov --junitxml=report.xml
