name: CI for Hello World
on:
  push:
    branches:
      - yamlTesting
  pull_request_target:
    branches:
      - sprint
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11          
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov		  
      - name: Checkout own repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"          
      - name: get QA Pytest
        run: |
          git --version
          git config user.name "Villicus-np"
          git config user.email "kevinkhew01@gmail.com"
          git status
          git checkout remotes/origin/main QA_Test.py
          
      - name: list our contents
        run: |
          ls
      - name: Test QA's script
        run: |
          pytest QA_Test.py -v -cov --junitxml=report.xml
        #continue-on-error: true        
      - if: failure()
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/missingFeatures.md
          update_existing: true
          search_existing: all
          
      - name: Test Dev's script
        run: |
          pytest Dev_Test.py -v -cov --junitxml=report.xml
      
      - if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          update_existing: true
          search_existing: all

      - name: Push to Dev Branch
        if: success()
        run: git push origin dev
