name: CI for QA Branch
on:
  push:
    branches:
      QABranch
    
jobs:
  testDevCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11  
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install selenium
          pip install webdriver-manager
          pip install Flask
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-Team5-2022/DevOps_Oct2022_Team5_Assignment
          fetch-depth: "0" 
      - name: Get Dev Code
        run: |
          git --version
          git config user.name "Villicus-np"
          git config user.email "kevinkhew01@gmail.com"
          git status
          git checkout remotes/origin/DevBranch main.py
          git checkout remotes/origin/DevBranch templates
          git checkout remotes/origin/DevBranch static/css
      - name: list our contents
        run: |
          ls
      - name: Check Chrome version
        run: google-chrome --version
      - name: Check ChromeDriver version
        run: chromedriver --version
      - name: Check Selenium version
        run: pip show selenium
      - name: Check environment
        run: pip list
      - name: Testing Dev's code
        run: |
          pytest QA_Test.py -v -cov --junitxml=QAReportDevCode.xml

