name: CI for QA Branch
on:
  push:
    branches:
      QABranch
    
jobs:
  testDevCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11  
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install selenium-yaml
          pip install webdriver-manager
          pip install Flask
      - uses: nanasess/setup-chromedriver@v1
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-Team5-2022/DevOps_Oct2022_Team5_Assignment
          fetch-depth: "0" 
      - name: Get Dev Code
        run: |
          git --version
          git config user.name "Villicus-np"
          git config user.email "kevinkhew01@gmail.com"
          git status
          git checkout remotes/origin/DevBranch main.py
      - name: list our contents
        run: |
          ls
      - name: Check Chrome version
        run: chrome --version
      - name: Check ChromeDriver version
        run: chromedriver --version
      - name: Check Selenium version
        run: python -m selenium -v
      - name: Testing Dev's code
        run: |
          pytest QA_Test.py -v -cov --junitxml=QAReportDevCode.xml
          
      - if: failure()
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          
      - name: send telegram message on test failure      
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_QA }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Issue: Testing of Dev's code from QA push has failed.
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "QAReportDevCode.xml"
      - name: create folder & move files
        if: always()
        run: |
          mkdir downloads
          mv *.xml ./downloads
      - name: Upload document
        if: always()
        uses: actions/upload-artifact@v2
        with: 
          name: QATestResultsDev
          path: downloads
      - name: Set environment version
        if: always()
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: download remote information
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: QATestResultsDev
      - name: Calculate project metrics
        if: always()
        id: projectmetrics
        run: |
          yarn
          yarn build
          SIZE=($(du -s dist/))
          echo "::set-output name=code_size::$SIZE"
      - uses: floric/repo-monitor-action@v1.4.1
        if: always()
        name: Update Report
        with:
          key: code-size
          value: ${{ steps.projectmetrics.outputs.code_size }}
          token: ${{ secrets.GITHUB_TOKEN }}
