name: CI for QA Branch
on:
  push:
    branches:
      QABranch
    
jobs:
  testDevCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11  
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install selenium-yaml
          pip install webdriver-manager
          pip install Flask
          sudo apt-get update 
          sudo apt-get install google-chrome-stable
          
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-Team5-2022/DevOps_Oct2022_Team5_Assignment
      - name: Get Dev Code
        run: |
          git --version
          git config user.name "Villicus-np"
          git config user.email "kevinkhew01@gmail.com"
          git status
          git checkout remotes/origin/DevBranch main.py
      - name: list our contents
        run: |
          ls
      - name: Testing Dev's code
        run: |
          pytest main.py -v -cov --junitxml=QAReportDevCode.xml
          
      - if: failure()
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          
      - name: send telegram message on test failure
      
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_QA }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Issue: Testing of Dev's code from QA push has failed.
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
